# Pentagonal numbers are generated by the formula,
# Pn=n(3n−1)/2. The first ten pentagonal numbers are:
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However,
# their difference, 70 − 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, Pj and Pk, for which
# their sum and difference are pentagonal and D = |Pk − Pj| is minimised;
# what is the value of D?



$pentagonal = Enumerator.new do |yielder|
  num = 1
  loop do
    yielder.yield(num * (3 * num - 1) / 2)
    num += 1
  end
end

def pentagonal?(num)
  $pentagonal.first(1_000).include? num
end

a =  $pentagonal.first(400).combination(2).to_a

a.select! { |elem| pentagonal?(elem[1] - elem[0]) && pentagonal?(elem[1] + elem[0])  }

puts a