# Each new term in the Fibonacci sequence is generated by adding -
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

fibonacci = Enumerator.new do |yielder|
  a = 1
  b = 2
  yielder.yield (1)
  yielder.yield (2)
  loop do
    yielder.yield a + b
    c = b
    b = a + b
    a = c
  end
end

puts fibonacci.first(100).select { |num| num.even? && num < 4_000_000 }.inject(:+)